// GENERATED BY THE COMMAND ABOVE; DO NOT EDIT
// This file was generated by swaggo/swag at
// 2019-12-09 17:09:58.4757832 +0700 +07 m=+0.055028201

package docs

import (
	"bytes"
	"encoding/json"
	"strings"

	"github.com/alecthomas/template"
	"github.com/swaggo/swag"
)

var doc = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{.Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "license": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/awaitpayment": {
            "get": {
                "description": "Hiển thị phiên đấu giá chưa thanh toán của người dùng. Cần phải đăng nhập để sử dụng. Trả về JSON form",
                "tags": [
                    "BidSession Controller"
                ],
                "summary": "Hiển thị phiên đấu giá chưa thanh toán",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Session token",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Success message",
                        "schema": {
                            "type": "body"
                        }
                    },
                    "400": {
                        "description": "Error message",
                        "schema": {
                            "type": "body"
                        }
                    },
                    "401": {
                        "description": "Error message",
                        "schema": {
                            "type": "body"
                        }
                    },
                    "500": {
                        "description": "Error message",
                        "schema": {
                            "type": "body"
                        }
                    }
                }
            }
        },
        "/categories": {
            "get": {
                "description": "Tìm categories bằng id, nhận id dưới dạng query, trả về toàn bộ tên categories nếu để trống.",
                "tags": [
                    "Categories Controller"
                ],
                "summary": "Tìm categories bằng id",
                "parameters": [
                    {
                        "type": "string",
                        "description": "id of categories, if empty then return all",
                        "name": "id",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/model.Categories"
                        }
                    },
                    "500": {
                        "description": "Error message",
                        "schema": {
                            "type": "body"
                        }
                    }
                }
            },
            "post": {
                "tags": [
                    "Categories Controller"
                ],
                "summary": "Tạo Categories mới (Administrator only)",
                "responses": {
                    "200": {
                        "description": "Success message",
                        "schema": {
                            "type": "body"
                        }
                    },
                    "500": {
                        "description": "Error message",
                        "schema": {
                            "type": "body"
                        }
                    }
                }
            }
        },
        "/history/bid": {
            "get": {
                "description": "Hiển thị những hoạt động đấu giá của user trên các session.",
                "tags": [
                    "BidSession Controller"
                ],
                "summary": "Hiển thị lịch sử đấu giá của user.",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Session token",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/model.BidHistory"
                        }
                    },
                    "400": {
                        "description": "Error message",
                        "schema": {
                            "type": "body"
                        }
                    },
                    "401": {
                        "description": "Error message",
                        "schema": {
                            "type": "body"
                        }
                    },
                    "500": {
                        "description": "Error message",
                        "schema": {
                            "type": "body"
                        }
                    }
                }
            }
        },
        "/history/sell": {
            "get": {
                "tags": [
                    "BidSession Controller"
                ],
                "summary": "Hiển thị lịch sử bán hàng của user",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Session token",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/model.SellHistory"
                        }
                    },
                    "400": {
                        "description": "Error message",
                        "schema": {
                            "type": "body"
                        }
                    },
                    "401": {
                        "description": "Error message",
                        "schema": {
                            "type": "body"
                        }
                    },
                    "500": {
                        "description": "Error message",
                        "schema": {
                            "type": "body"
                        }
                    }
                }
            }
        },
        "/lock/:sessionid": {
            "put": {
                "tags": [
                    "BidSession Controller"
                ],
                "summary": "Khóa phiên đấu giá (API nội bộ, không public cho user)",
                "parameters": [
                    {
                        "type": "string",
                        "description": "session ID",
                        "name": "SessionID",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Success message",
                        "schema": {
                            "type": "body"
                        }
                    },
                    "400": {
                        "description": "Error message",
                        "schema": {
                            "type": "body"
                        }
                    },
                    "401": {
                        "description": "Error message",
                        "schema": {
                            "type": "body"
                        }
                    },
                    "500": {
                        "description": "Error message",
                        "schema": {
                            "type": "body"
                        }
                    }
                }
            }
        },
        "/login": {
            "post": {
                "description": "Đăng nhập bằng JSON form, trả về session token nếu thành công.",
                "tags": [
                    "Logging Controller"
                ],
                "summary": "Đăng nhập bằng JSON",
                "parameters": [
                    {
                        "description": "Login Information",
                        "name": "LoginForm",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model.LoginForm"
                        }
                    },
                    {
                        "description": "password",
                        "name": "password",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "string"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Session token",
                        "schema": {
                            "type": "body"
                        }
                    },
                    "400": {
                        "description": "Error message",
                        "schema": {
                            "type": "body"
                        }
                    },
                    "500": {
                        "description": "Error message",
                        "schema": {
                            "type": "body"
                        }
                    }
                }
            }
        },
        "/logs": {
            "post": {
                "description": "Nhận thông tin đấu giá dưới dạng JSON, sau đó kiểm tra quyền đấu giá của user (người dùng không thể ra giá chính phiên của mình). Trả về message JSON thông báo",
                "tags": [
                    "Bidding Log Controller"
                ],
                "summary": "Ra giá trong một Session",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Session token",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "Information to be provided",
                        "name": "NewBidInfo",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model.NewBidLog"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Success message",
                        "schema": {
                            "type": "body"
                        }
                    },
                    "400": {
                        "description": "Error message",
                        "schema": {
                            "type": "body"
                        }
                    },
                    "401": {
                        "description": "Error message",
                        "schema": {
                            "type": "body"
                        }
                    },
                    "500": {
                        "description": "Error message",
                        "schema": {
                            "type": "body"
                        }
                    }
                }
            }
        },
        "/logs/:sessionid": {
            "get": {
                "description": "Nhận thông tin session_id dưới dạng Path, sau đó trả về toàn bộ lịch sử đấu giá của id đó.",
                "tags": [
                    "Bidding Log Controller"
                ],
                "summary": "Lấy lịch sử đấu giá của một Session",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Session id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/model.BidSessionLog"
                        }
                    },
                    "500": {
                        "description": "Error message",
                        "schema": {
                            "type": "body"
                        }
                    }
                }
            }
        },
        "/logs/last": {
            "delete": {
                "description": "Xóa lần ra giá gần nhất của phiên đấu giá.",
                "tags": [
                    "Bidding Log Controller"
                ],
                "summary": "Xóa lần ra giá gần nhất (Administrator only)",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Session token",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "Bid Log info",
                        "name": "LogInfo",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model.Deletelastlog"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Success message",
                        "schema": {
                            "type": "body"
                        }
                    },
                    "400": {
                        "description": "Error message",
                        "schema": {
                            "type": "body"
                        }
                    },
                    "401": {
                        "description": "Error message",
                        "schema": {
                            "type": "body"
                        }
                    },
                    "500": {
                        "description": "Error message",
                        "schema": {
                            "type": "body"
                        }
                    }
                }
            }
        },
        "/password": {
            "put": {
                "tags": [
                    "User Controller"
                ],
                "summary": "Đổi mất khẩu người dùng",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Session token",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "Information to be provided",
                        "name": "Passwordinfo",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model.ModifyPassword"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Success message",
                        "schema": {
                            "type": "body"
                        }
                    },
                    "400": {
                        "description": "Error message",
                        "schema": {
                            "type": "body"
                        }
                    },
                    "401": {
                        "description": "Error message",
                        "schema": {
                            "type": "body"
                        }
                    },
                    "500": {
                        "description": "Error message",
                        "schema": {
                            "type": "body"
                        }
                    }
                }
            }
        },
        "/profile": {
            "get": {
                "tags": [
                    "User Controller"
                ],
                "summary": "Hiển thị thông tin cá nhân người dùng",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Session token",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/model.UserCommon"
                        }
                    },
                    "400": {
                        "description": "Error message",
                        "schema": {
                            "type": "body"
                        }
                    },
                    "401": {
                        "description": "Error message",
                        "schema": {
                            "type": "body"
                        }
                    },
                    "500": {
                        "description": "Error message",
                        "schema": {
                            "type": "body"
                        }
                    }
                }
            },
            "put": {
                "tags": [
                    "User Controller"
                ],
                "summary": "Thay đổi thông tin cá nhân người dùng",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Session token",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Success message",
                        "schema": {
                            "type": "body"
                        }
                    },
                    "400": {
                        "description": "Error message",
                        "schema": {
                            "type": "body"
                        }
                    },
                    "401": {
                        "description": "Error message",
                        "schema": {
                            "type": "body"
                        }
                    },
                    "500": {
                        "description": "Error message",
                        "schema": {
                            "type": "body"
                        }
                    }
                }
            }
        },
        "/review": {
            "post": {
                "description": "Tạo review từ user đến user khác. Review phải được đính với id session đấu già mà user đó thắng. Mỗi id session chỉ có duy nhất 1 review. Một user không thể review chính bản thân mình.",
                "tags": [
                    "Review Controller"
                ],
                "summary": "Tạo review mới",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Session token",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "Information to be provided",
                        "name": "NewSessionInfo",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model.NewReview"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Success message",
                        "schema": {
                            "type": "body"
                        }
                    },
                    "400": {
                        "description": "Error message",
                        "schema": {
                            "type": "body"
                        }
                    },
                    "401": {
                        "description": "Error message",
                        "schema": {
                            "type": "body"
                        }
                    },
                    "500": {
                        "description": "Error message",
                        "schema": {
                            "type": "body"
                        }
                    }
                }
            }
        },
        "/review/:sessionid": {
            "delete": {
                "tags": [
                    "Review Controller"
                ],
                "summary": "Xóa review của user dựa theo session id (administrator only)",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Session token",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "ID session",
                        "name": "sessionID",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Success message",
                        "schema": {
                            "type": "body"
                        }
                    },
                    "400": {
                        "description": "Error message",
                        "schema": {
                            "type": "body"
                        }
                    },
                    "401": {
                        "description": "Error message",
                        "schema": {
                            "type": "body"
                        }
                    },
                    "500": {
                        "description": "Error message",
                        "schema": {
                            "type": "body"
                        }
                    }
                }
            }
        },
        "/review/:userid": {
            "get": {
                "description": "Lấy review bằng userid dưới dạng path, trả về form JSON.",
                "tags": [
                    "Review Controller"
                ],
                "summary": "Lấy review bằng userid",
                "parameters": [
                    {
                        "type": "string",
                        "description": "User id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/model.UserReview"
                        }
                    },
                    "500": {
                        "description": "Error message",
                        "schema": {
                            "type": "body"
                        }
                    }
                }
            }
        },
        "/session": {
            "get": {
                "description": "Tìm phiên đấu giá bằng tên mặt hàng và/hoặc categories. Tên mặt hàng không cần viết đầy đủ. Trả về tất cả nếu để trống. Trả về JSON form",
                "tags": [
                    "BidSession Controller"
                ],
                "summary": "Tìm phiên đấu giá bằng tên mặt hàng và/hoặc categories",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Name of the item (or part of it)",
                        "name": "name",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Item Categories by number",
                        "name": "categories",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/model.SessionSearch"
                        }
                    },
                    "500": {
                        "description": "Error message",
                        "schema": {
                            "type": "body"
                        }
                    }
                }
            },
            "put": {
                "tags": [
                    "BidSession Controller"
                ],
                "summary": "Thay đổi thông tin phiên đấu giá.",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Session token",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "Information to be provided",
                        "name": "NewSessionInfo",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model.UpdateSession"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Success message",
                        "schema": {
                            "type": "body"
                        }
                    },
                    "400": {
                        "description": "Error message",
                        "schema": {
                            "type": "body"
                        }
                    },
                    "401": {
                        "description": "Error message",
                        "schema": {
                            "type": "body"
                        }
                    },
                    "500": {
                        "description": "Error message",
                        "schema": {
                            "type": "body"
                        }
                    }
                }
            },
            "post": {
                "tags": [
                    "BidSession Controller"
                ],
                "summary": "Tạo phiên đấu giá mới",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Session token",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "Information to be provided",
                        "name": "NewSessionInfo",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model.NewSession"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Success message",
                        "schema": {
                            "type": "body"
                        }
                    },
                    "400": {
                        "description": "Error message",
                        "schema": {
                            "type": "body"
                        }
                    },
                    "401": {
                        "description": "Error message",
                        "schema": {
                            "type": "body"
                        }
                    },
                    "500": {
                        "description": "Error message",
                        "schema": {
                            "type": "body"
                        }
                    }
                }
            }
        },
        "/session/:sessionid": {
            "get": {
                "description": "Tìm phiên đáu giá bằng id dưới dạng path, trả về JSON form",
                "tags": [
                    "BidSession Controller"
                ],
                "summary": "Tìm phiên đấu giá bằng id",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Session id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/model.SessionSearch"
                        }
                    },
                    "500": {
                        "description": "Error message",
                        "schema": {
                            "type": "body"
                        }
                    }
                }
            },
            "delete": {
                "description": "Xóa toàn bộ phiên đấu giá và các dữ liệu liên quan như lịch sử đấu giá, thông tin mặt hàng của phiên đấu giá.",
                "tags": [
                    "BidSession Controller"
                ],
                "summary": "Xóa phiên đấu giá (Administrator only)",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Session token",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "session id to be deleted",
                        "name": "sessionid",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Success message",
                        "schema": {
                            "type": "body"
                        }
                    },
                    "400": {
                        "description": "Error message",
                        "schema": {
                            "type": "body"
                        }
                    },
                    "401": {
                        "description": "Error message",
                        "schema": {
                            "type": "body"
                        }
                    },
                    "500": {
                        "description": "Error message",
                        "schema": {
                            "type": "body"
                        }
                    }
                }
            }
        },
        "/signup": {
            "post": {
                "description": "Tạo tài khoản mới bằng JSON form, trả về session token nếu thành công.",
                "tags": [
                    "Logging Controller"
                ],
                "summary": "Tạo tài khoản mới",
                "parameters": [
                    {
                        "description": "Resgister Information",
                        "name": "RegisterInfo",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model.RegisterForm"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Session token",
                        "schema": {
                            "type": "body"
                        }
                    },
                    "400": {
                        "description": "Error message",
                        "schema": {
                            "type": "body"
                        }
                    },
                    "500": {
                        "description": "Error message",
                        "schema": {
                            "type": "body"
                        }
                    }
                }
            }
        },
        "/upload": {
            "post": {
                "description": "Upload one or multiples photos of item , return a JSON message",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Session token",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Item id to be removed from wishlist",
                        "name": "itemid",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Success message",
                        "schema": {
                            "type": "body"
                        }
                    },
                    "400": {
                        "description": "Error message",
                        "schema": {
                            "type": "body"
                        }
                    },
                    "401": {
                        "description": "Error message",
                        "schema": {
                            "type": "body"
                        }
                    },
                    "500": {
                        "description": "Error message",
                        "schema": {
                            "type": "body"
                        }
                    }
                }
            }
        },
        "/wishlist": {
            "get": {
                "tags": [
                    "Wishlist Controller"
                ],
                "summary": "Hiển thị danh sách đánh dấu session của user",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Session token",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/model.Items"
                        }
                    },
                    "400": {
                        "description": "Error message",
                        "schema": {
                            "type": "body"
                        }
                    },
                    "401": {
                        "description": "Error message",
                        "schema": {
                            "type": "body"
                        }
                    },
                    "500": {
                        "description": "Error message",
                        "schema": {
                            "type": "body"
                        }
                    }
                }
            }
        },
        "/wishlist/:itemid": {
            "post": {
                "tags": [
                    "Wishlist Controller"
                ],
                "summary": "Thêm session vào danh sách đánh dấu của user",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Session token",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Item id to be added to wishlist",
                        "name": "itemid",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Success message",
                        "schema": {
                            "type": "body"
                        }
                    },
                    "400": {
                        "description": "Error message",
                        "schema": {
                            "type": "body"
                        }
                    },
                    "401": {
                        "description": "Error message",
                        "schema": {
                            "type": "body"
                        }
                    },
                    "500": {
                        "description": "Error message",
                        "schema": {
                            "type": "body"
                        }
                    }
                }
            },
            "delete": {
                "tags": [
                    "Wishlist Controller"
                ],
                "summary": "Xóa session khỏi danh sách đánh dấu",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Session token",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Item id to be removed from wishlist",
                        "name": "itemid",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Success message",
                        "schema": {
                            "type": "body"
                        }
                    },
                    "400": {
                        "description": "Error message",
                        "schema": {
                            "type": "body"
                        }
                    },
                    "401": {
                        "description": "Error message",
                        "schema": {
                            "type": "body"
                        }
                    },
                    "500": {
                        "description": "Error message",
                        "schema": {
                            "type": "body"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "model.BidHistory": {
            "type": "object",
            "properties": {
                "bidamount": {
                    "type": "integer"
                },
                "biddate": {
                    "type": "string"
                },
                "images": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "itemid": {
                    "type": "integer"
                },
                "itemname": {
                    "type": "string"
                },
                "sessionenddate": {
                    "type": "string"
                },
                "sessionid": {
                    "type": "integer"
                },
                "sessionstartdate": {
                    "type": "string"
                }
            }
        },
        "model.BidSessionLog": {
            "type": "object",
            "properties": {
                "amount": {
                    "type": "integer"
                },
                "createAt": {
                    "type": "string"
                },
                "sessionid": {
                    "type": "integer"
                },
                "userid": {
                    "type": "string"
                }
            }
        },
        "model.Categories": {
            "type": "object",
            "properties": {
                "categoriesid": {
                    "type": "integer"
                },
                "categoriesname": {
                    "type": "string"
                }
            }
        },
        "model.Deletelastlog": {
            "type": "object",
            "required": [
                "sessionid",
                "userid"
            ],
            "properties": {
                "sessionid": {
                    "type": "integer"
                },
                "userid": {
                    "type": "string"
                }
            }
        },
        "model.Items": {
            "type": "object",
            "properties": {
                "categoriesid": {
                    "type": "integer"
                },
                "createAt": {
                    "type": "string"
                },
                "itemcondition": {
                    "type": "string"
                },
                "itemdescription": {
                    "type": "string"
                },
                "itemid": {
                    "type": "integer"
                },
                "itemname": {
                    "type": "string"
                }
            }
        },
        "model.LoginForm": {
            "type": "object",
            "required": [
                "password",
                "userid"
            ],
            "properties": {
                "password": {
                    "type": "string"
                },
                "userid": {
                    "type": "string"
                }
            }
        },
        "model.ModifyPassword": {
            "type": "object",
            "required": [
                "newpassword",
                "oldpassword"
            ],
            "properties": {
                "newpassword": {
                    "type": "string"
                },
                "oldpassword": {
                    "type": "string"
                }
            }
        },
        "model.NewBidLog": {
            "type": "object",
            "required": [
                "amount",
                "sessionid"
            ],
            "properties": {
                "amount": {
                    "type": "integer"
                },
                "sessionid": {
                    "type": "integer"
                }
            }
        },
        "model.NewReview": {
            "type": "object",
            "required": [
                "reviewcontent",
                "reviewscore",
                "sessionid",
                "usertargetid"
            ],
            "properties": {
                "reviewcontent": {
                    "type": "string"
                },
                "reviewscore": {
                    "type": "integer"
                },
                "sessionid": {
                    "type": "integer"
                },
                "usertargetid": {
                    "type": "string"
                }
            }
        },
        "model.NewSession": {
            "type": "object",
            "required": [
                "categoriesid",
                "itemcondition",
                "itemdescription",
                "itemname",
                "minimumincreasebid",
                "startprice"
            ],
            "properties": {
                "categoriesid": {
                    "type": "integer"
                },
                "enddate": {
                    "type": "string"
                },
                "imagelink": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "itemcondition": {
                    "type": "string"
                },
                "itemdescription": {
                    "type": "string"
                },
                "itemname": {
                    "type": "string"
                },
                "minimumincreasebid": {
                    "type": "integer"
                },
                "startdate": {
                    "type": "string"
                },
                "startprice": {
                    "type": "integer"
                }
            }
        },
        "model.RegisterForm": {
            "type": "object",
            "required": [
                "email",
                "password",
                "userid"
            ],
            "properties": {
                "email": {
                    "type": "string"
                },
                "password": {
                    "type": "string"
                },
                "userid": {
                    "type": "string"
                }
            }
        },
        "model.SellHistory": {
            "type": "object",
            "properties": {
                "images": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "itemid": {
                    "type": "integer"
                },
                "itemname": {
                    "type": "string"
                },
                "sessionenddate": {
                    "type": "string"
                },
                "sessionid": {
                    "type": "integer"
                },
                "sessionstartdate": {
                    "type": "string"
                }
            }
        },
        "model.SessionSearch": {
            "type": "object",
            "required": [
                "categoriesid",
                "currentbid",
                "itemcondition",
                "itemdescription",
                "itemname",
                "minimumincreasebid"
            ],
            "properties": {
                "biddingLog": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/model.BidSessionLog"
                    }
                },
                "categoriesid": {
                    "type": "integer"
                },
                "categoriesname": {
                    "type": "string"
                },
                "currentbid": {
                    "type": "integer"
                },
                "enddate": {
                    "type": "string"
                },
                "imagelink": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "itemcondition": {
                    "type": "string"
                },
                "itemdescription": {
                    "type": "string"
                },
                "itemid": {
                    "type": "integer"
                },
                "itemname": {
                    "type": "string"
                },
                "minimumincreasebid": {
                    "type": "integer"
                },
                "sellerid": {
                    "type": "string"
                },
                "sellername": {
                    "type": "string"
                },
                "sessionid": {
                    "type": "integer"
                },
                "sessionstatus": {
                    "type": "string"
                },
                "startdate": {
                    "type": "string"
                },
                "viewcount": {
                    "type": "integer"
                }
            }
        },
        "model.UpdateSession": {
            "type": "object",
            "required": [
                "sessionid"
            ],
            "properties": {
                "itemcondition": {
                    "type": "string"
                },
                "itemdescription": {
                    "type": "string"
                },
                "itemname": {
                    "type": "string"
                },
                "sessionid": {
                    "type": "integer"
                }
            }
        },
        "model.UserCommon": {
            "type": "object",
            "properties": {
                "accesslevel": {
                    "type": "integer"
                },
                "address": {
                    "type": "string"
                },
                "avatarimage": {
                    "type": "string"
                },
                "createAt": {
                    "type": "string"
                },
                "email": {
                    "type": "string"
                },
                "gender": {
                    "type": "integer"
                },
                "name": {
                    "type": "string"
                },
                "password": {
                    "type": "string"
                },
                "phone": {
                    "type": "string"
                },
                "userid": {
                    "type": "string"
                }
            }
        },
        "model.UserReview": {
            "type": "object",
            "properties": {
                "content": {
                    "type": "string"
                },
                "score": {
                    "type": "integer"
                },
                "sessionid": {
                    "type": "integer"
                },
                "targetid": {
                    "type": "string"
                },
                "writerid": {
                    "type": "string"
                }
            }
        }
    }
}`

type swaggerInfo struct {
	Version     string
	Host        string
	BasePath    string
	Schemes     []string
	Title       string
	Description string
}

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = swaggerInfo{
	Version:     "",
	Host:        "",
	BasePath:    "",
	Schemes:     []string{},
	Title:       "",
	Description: "",
}

type s struct{}

func (s *s) ReadDoc() string {
	sInfo := SwaggerInfo
	sInfo.Description = strings.Replace(sInfo.Description, "\n", "\\n", -1)

	t, err := template.New("swagger_info").Funcs(template.FuncMap{
		"marshal": func(v interface{}) string {
			a, _ := json.Marshal(v)
			return string(a)
		},
	}).Parse(doc)
	if err != nil {
		return doc
	}

	var tpl bytes.Buffer
	if err := t.Execute(&tpl, sInfo); err != nil {
		return doc
	}

	return tpl.String()
}

func init() {
	swag.Register(swag.Name, &s{})
}
